CREATE TABLE IF NOT EXISTS admin (AID int(11) NOT NULL AUTO_INCREMENT,ANAME varchar(50)NOT NULL,APASS varchar(50) NOT NULL,PRIMARY KEY(AID))ENGINE=INNODB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1; 




CREATE TABLE IF NOT EXISTS book (BID int(11) NOT NULL AUTO_INCREMENT,BTITLE varchar(100) NOT NULL,KEYWORDS varchar(100) NOT NULL,FILE varchar(150) NOT NULL,PRIMARY KEY(BID))ENGINE=INNODB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;




CREATE TABLE IF NOT EXISTS comment(CID int(11) NOT NULL AUTO_INCREMENT,BID int(11) NOT NULL,SID int(11) NOT NULL,COMM varchar(150)NOT NULL, LOGGS date NOT NULL,PRIMARY KEY(CID))ENGINE=INNODB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;





CREATE TABLE IF NOT EXISTS request(RID int(11) NOT NULL AUTO_INCREMENT,ID int(11)NOT NULL,MES text NOT NULL,LOGGS datetime NOT NULL,PRIMARY KEY(RID))ENGINE=INNODB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;





CREATE TABLE IF NOT EXISTS student(ID int(11) NOT NULL AUTO_INCREMENT,NAME varchar(50) NOT NULL,PASS varchar(150)NOT NULL,MAIL varchar(150)NOT NULL,DEP varchar(100)NOT NULL,PRIMARY KEY(ID))ENGINE=INNODB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;